export const categories = [
  {
    id: "01",
    category: "Breakfast",
  },
  {
    id: "02",
    category: "Lunch",
  },
  {
    id: "03",
    category: "Dinner",
  },
  {
    id: "04",
    category: "Asian",
  },
  {
    id: "05",
    category: "Thai",
  },
  {
    id: "06",
    category: "Indian",
  },
];

export const recipeList = [
  {
    id: "1",
    name: "Spaghetti Bolognese",
    image: require("../../assets/images/spagetti.png"),
    rating: 4.8,
    ingredients: [
      "Spaghetti",
      "Minced beef",
      "Tomato sauce",
      "Garlic",
      "Onion",
    ],
    time: "45 mins",
    difficulty: "Medium",
    calories: 550,
    color: "#FF5733",
    description:
      "A classic Italian pasta dish with rich, meaty tomato sauce, seasoned with garlic and onions.",
    steps: [
      "Boil the spaghetti according to the package instructions.",
      "In a pan, sauté garlic and onions until fragrant.",
      "Add minced beef and cook until browned.",
      "Pour in tomato sauce and let it simmer for 15 minutes.",
      "Serve the sauce over the spaghetti and enjoy.",
    ],
  },
  {
    id: "2",
    name: "Chicken Curry",
    image: require("../../assets/images/chicken.png"),
    rating: 4.7,
    ingredients: ["Chicken", "Coconut milk", "Curry powder", "Garlic", "Onion"],
    time: "40 mins",
    difficulty: "Medium",
    calories: 600,
    color: "#FFA500",
    description:
      "A flavorful and creamy chicken curry made with coconut milk and aromatic spices.",
    steps: [
      "Heat oil in a pan and sauté garlic and onions.",
      "Add chicken pieces and cook until browned.",
      "Sprinkle curry powder and mix well.",
      "Pour in coconut milk and let it simmer for 20 minutes.",
      "Serve hot with rice or bread.",
    ],
  },
  {
    id: "3",
    name: "Caesar Salad",
    image: require("../../assets/images/cease.png"),
    rating: 4.5,
    ingredients: [
      "Lettuce",
      "Croutons",
      "Chicken",
      "Parmesan",
      "Caesar dressing",
    ],
    time: "20 mins",
    difficulty: "Easy",
    calories: 350,
    color: "#6FAE75",
    description:
      "A refreshing salad with crisp lettuce, grilled chicken, crunchy croutons, and creamy Caesar dressing.",
    steps: [
      "Chop lettuce and place it in a bowl.",
      "Grill the chicken and slice it into thin pieces.",
      "Add croutons and grated Parmesan cheese.",
      "Drizzle Caesar dressing over the salad and toss well.",
      "Serve immediately and enjoy.",
    ],
  },
  {
    id: "4",
    name: "Beef Burger",
    image: require("../../assets/images/beef.png"),
    rating: 4.9,
    ingredients: [
      "Beef patty",
      "Bun",
      "Lettuce",
      "Cheese",
      "Tomato",
      "Pickles",
    ],
    time: "30 mins",
    difficulty: "Medium",
    calories: 700,
    color: "#A52A2A",
    description:
      "A juicy beef burger stacked with fresh vegetables, cheese, and pickles, served in a soft bun.",
    steps: [
      "Grill or pan-fry the beef patty until fully cooked.",
      "Toast the burger buns lightly.",
      "Assemble the burger by adding lettuce, tomato, cheese, and pickles.",
      "Place the beef patty inside the bun.",
      "Serve with fries or a side salad.",
    ],
  },
  {
    id: "5",
    name: "Vegetable Stir Fry",
    image: require("../../assets/images/vegitable.png"),
    rating: 4.6,
    ingredients: ["Carrot", "Bell peppers", "Broccoli", "Soy sauce", "Ginger"],
    time: "25 mins",
    difficulty: "Easy",
    calories: 300,
    color: "#FFD700",
    description:
      "A quick and healthy vegetable stir-fry with soy sauce and ginger, packed with flavor and crunch.",
    steps: [
      "Chop all the vegetables into bite-sized pieces.",
      "Heat oil in a pan and sauté ginger until fragrant.",
      "Add vegetables and stir-fry for 5-7 minutes.",
      "Pour in soy sauce and mix well.",
      "Serve hot with rice or noodles.",
    ],
  },
  {
    id: "6",
    name: "Margherita Pizza",
    image: require("../../assets/images/pizza.png"),
    rating: 4.8,
    ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Basil"],
    time: "50 mins",
    difficulty: "Medium",
    calories: 800,
    color: "#DC143C",
    description:
      "A traditional Italian pizza topped with fresh tomato sauce, mozzarella cheese, and basil leaves.",
    steps: [
      "Preheat the oven to 220°C (425°F).",
      "Roll out the pizza dough on a baking tray.",
      "Spread tomato sauce evenly over the dough.",
      "Add mozzarella cheese and basil leaves on top.",
      "Bake for 15-20 minutes until golden brown.",
    ],
  },
  {
    id: "7",
    name: "Pancakes",
    image: require("../../assets/images/pan.png"),
    rating: 4.7,
    ingredients: ["Flour", "Milk", "Eggs", "Sugar", "Baking powder"],
    time: "20 mins",
    difficulty: "Easy",
    calories: 400,
    color: "yellow",
    description:
      "Soft and fluffy pancakes, perfect for breakfast, served with syrup or fresh fruit.",
    steps: [
      "Mix flour, baking powder, sugar, eggs, and milk in a bowl.",
      "Heat a pan and lightly grease it.",
      "Pour a small amount of batter onto the pan.",
      "Cook until bubbles appear, then flip to cook the other side.",
      "Serve with syrup or fresh fruit.",
    ],
  },
  {
    id: "8",
    name: "Grilled Salmon",
    image: require("../../assets/images/grill.png"),
    rating: 4.9,
    ingredients: ["Salmon", "Lemon", "Garlic", "Olive oil", "Salt", "Pepper"],
    time: "35 mins",
    difficulty: "Medium",
    calories: 500,
    color: "#FF4500",
    description:
      "A healthy and delicious grilled salmon fillet, seasoned with garlic, lemon, and olive oil.",
    steps: [
      "Preheat the grill to medium heat.",
      "Season the salmon with salt, pepper, garlic, and lemon juice.",
      "Brush with olive oil and place on the grill.",
      "Grill for 5-7 minutes on each side.",
      "Serve with a side of vegetables or salad.",
    ],
  },
  {
    id: "9",
    name: "Tacos",
    image: require("../../assets/images/taco.png"),
    rating: 4.6,
    ingredients: ["Tortilla", "Ground beef", "Lettuce", "Cheese", "Salsa"],
    time: "30 mins",
    difficulty: "Easy",
    calories: 450,
    color: "#D2691E",
    description:
      "Tasty and crunchy tacos filled with seasoned ground beef, fresh lettuce, cheese, and salsa.",
    steps: [
      "Cook the ground beef with spices until fully browned.",
      "Warm the tortillas in a pan.",
      "Fill each tortilla with beef, lettuce, cheese, and salsa.",
      "Fold the tortilla and serve immediately.",
      "Enjoy with a side of guacamole or sour cream.",
    ],
  },
  {
    id: "10",
    name: "Chocolate Cake",
    image: require("../../assets/images/choco.png"),
    rating: 4.8,
    ingredients: ["Flour", "Cocoa powder", "Sugar", "Eggs", "Butter"],
    time: "1 hr",
    difficulty: "Hard",
    calories: 900,
    color: "#4B0082",
    description:
      "A rich and moist chocolate cake with deep cocoa flavor, perfect for dessert lovers.",
    steps: [
      "Preheat the oven to 180°C (350°F).",
      "Mix flour, cocoa powder, sugar, eggs, and butter in a bowl.",
      "Pour the batter into a greased baking pan.",
      "Bake for 40-45 minutes until fully cooked.",
      "Let it cool before serving.",
    ],
  },
];
